# Generated by Django 6.0.4 on 2026-09-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado'), ('AUSENTE', 'Ausente')], max_length=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_reserva', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'turno',
                'managed': False,
            },
        ),
    ]
