# Generated by Django 6.0.4 on 2026-06-19 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barberia',
            fields=[
                ('id_barberia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('duenio', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Barberia',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Servicio',
            },
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Cliente',
        ),
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('id_profesional', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('red_social', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('id_barberia', models.ForeignKey(db_column='id_barberia', on_delete=django.db.models.deletion.PROTECT, to='usuarios.barberia')),
            ],
            options={
                'db_table': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_calificaciones', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('puntaje', models.PositiveSmallIntegerField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
                ('id_profesional', models.ForeignKey(db_column='id_profesional', on_delete=django.db.models.deletion.PROTECT, to='usuarios.profesionales')),
            ],
            options={
                'db_table': 'Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='BarberiaServicio',
            fields=[
                ('id_barberia_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('id_barberia', models.ForeignKey(db_column='id_barberia', on_delete=django.db.models.deletion.PROTECT, to='usuarios.barberia')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, to='usuarios.servicio')),
            ],
            options={
                'db_table': 'Barberia_Servicio',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('reservado', 'Reservado'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado')], default='libre', max_length=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('monto_propina', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('id_barberia', models.ForeignKey(db_column='id_barberia', on_delete=django.db.models.deletion.PROTECT, to='usuarios.barberia')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
                ('id_profesional', models.ForeignKey(db_column='id_profesional', on_delete=django.db.models.deletion.PROTECT, to='usuarios.profesionales')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, to='usuarios.servicio')),
            ],
            options={
                'db_table': 'Turno',
            },
        ),
    ]
